services:
    app:
        image: "node:14"
        container_name: "${APP_NAME}-app"
        volumes: ["./:/home/docker"]
        working_dir: "/home/docker"
        ports: ["127.0.0.1:48200:3000"]
        networks: ["proxy"]
        tty: true
        user: "1000"
        command: "npm run dev"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.${APP_NAME}-app.rule=Host(`${APP_NAME}.localhost`)"
            - "traefik.http.routers.${APP_NAME}-app.service=${APP_NAME}-app"
            - "traefik.http.routers.${APP_NAME}-app.entrypoints=web"
            - "traefik.http.services.${APP_NAME}-app.loadbalancer.server.port=3000"

networks:
    proxy: { name: "proxy" }
